### ISSUE TITLE
[REQ] - 

### ISSUE THREAD

**Issue by micron888** [ExtremeFiretop/MerlinAutoUpdate-Router#89]
please consider adding gnuton firmware
https://github.com/gnuton/asuswrt-merlin.ng

**Comment by Martinski4GitHub** [comment]
> please consider adding gnuton firmware https://github.com/gnuton/asuswrt-merlin.ng
>
We have placed some restrictions on what routers to support based on RMerlin's advice:

https://www.snbforums.com/threads/introducing-merlinau-the-ultimate-firmware-auto-updater-addon.88577/page-2#post-887594

So at the moment, only **HND** models & routers that are **not** End-of-Life are supported. 
Given those restrictions, if your F/W versioning string follows the same format as RMerlin's F/W (e.g. "**386.12_4**", "**3004_388.6_0**") in both NVRAM-related vars & downloadable F/W zip files, it might be possible. Ultimately, it will also depend on whether one of us has a router model to test with your F/W; otherwise, it becomes difficult to support a platform on which we cannot test at all.

**Comment by ExtremeFiretop** [comment]
> please consider adding gnuton firmware https://github.com/gnuton/asuswrt-merlin.ng

The current logic also pulls from SF and uses the routers model and built in updater to get the versioning to construct the URL to get the update...

I don't know enough about gnuton since I don't have a router that supports the firmware, but ultimately I would say the biggest challenge would likely be how it's hosted if it's only hosted on Github and not on a public repo like SourceForge.

Github has the infrastructure to support high downloads, but finding and sparing through a webpage with a bunch of different models and versions becomes less accurate than the route currently taken.

**Comment by ExtremeFiretop** [comment]
@micron888 

Can you provide me the output of: 

`for nvramKey in productid build_name odmpid; do routerProductID=$(nvram get "$nvramKey") && [ -n "$routerProductID" ] && echo "$routerProductID" && break; done`

And:

`for nvramKey in productid build_name odmpid; do routerProductID="$(nvram get "$nvramKey")"; [ -n "$routerProductID" ] && echo "$routerProductID" && break; done`

Also can you provide the output of:

`nvram get buildno
`
and 

`nvram get build_name`

Thanks!

**Comment by ExtremeFiretop** [comment]
@micron888 

Also the output of: 

`nvram get buildinfo`

**Comment by ExtremeFiretop** [comment]
@micron888 

This is as close as I can get without the info above: 
https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/tree/GnutonF/W

I suspect there will still be issues with the following code:

```
    if ! release_version="$(_GetLatestFWUpdateVersionFromRouter_)" || \
       ! _CheckNewUpdateFirmwareNotification_ "$current_version" "$release_version"
    then
        Say "No new firmware version update is found for [$PRODUCT_ID] router model."
        "$inMenuMode" && _WaitForEnterKey_ "$menuReturnPromptStr"
        return 1
    fi
```

But i don't have hardware to test. 
If you find a dev on gnuton that wants to fork that branch and finish it, feel free :)

**Comment by ExtremeFiretop** [comment]
@micron888 

We need your contact information please and thanks.

**Comment by ExtremeFiretop** [comment]
This was completed in PR: https://github.com/ExtremeFiretop/MerlinAutoUpdate-Router/pull/186
It's now merged into the dev branch, and will likely be apart of the next release.

Thanks for suggestion :)
